included:
  - RogerVoice/

excluded:
  - RogerVoice/Base.lproj/
  - RogerVoice/Resources/

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_assert
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - last_where
  - legacy_objc_type
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - prefer_self_in_static_references
  - prefer_zero_over_explicit_init
  - redundant_type_annotation
  - sorted_first_last
 # - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
    # - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - yoda_condition

empty_parentheses_with_trailing_closure:
  severity: error

file_length:
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

identifier_name:
  excluded: ["id", "ID", "T", "U"]
  allowed_symbols: ["_"]

type_name:
  excluded: ["ID"]

legacy_constant:
  severity: error

legacy_constructor:
  severity: error

trailing_comma:
  mandatory_comma: true

trailing_semicolon:
  severity: error

void_return:
  severity: error

anyobject_protocol:
  severity: error

discouraged_object_literal:
  severity: error

empty_collection_literal:
  severity: error

enum_case_associated_values_count:
  warning: 3
  error: 4

explicit_init:
  severity: error

weak_delegate:
  severity: error

yoda_condition:
  severity: error

multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true

cyclomatic_complexity:
